// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CSMXP_V3.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_CSMXP_V3_H_
#define _FAST_DDS_GENERATED_CSMXP_V3_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(CSMXP_V3_SOURCE)
#define CSMXP_V3_DllAPI __declspec( dllexport )
#else
#define CSMXP_V3_DllAPI __declspec( dllimport )
#endif // CSMXP_V3_SOURCE
#else
#define CSMXP_V3_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define CSMXP_V3_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure CSMXP_V3 defined by the user in the IDL file.
 * @ingroup CSMXP_V3
 */
class CSMXP_V3
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport CSMXP_V3();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~CSMXP_V3();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object CSMXP_V3 that will be copied.
     */
    eProsima_user_DllExport CSMXP_V3(
            const CSMXP_V3& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object CSMXP_V3 that will be copied.
     */
    eProsima_user_DllExport CSMXP_V3(
            CSMXP_V3&& x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object CSMXP_V3 that will be copied.
     */
    eProsima_user_DllExport CSMXP_V3& operator =(
            const CSMXP_V3& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object CSMXP_V3 that will be copied.
     */
    eProsima_user_DllExport CSMXP_V3& operator =(
            CSMXP_V3&& x);

    /*!
     * @brief Comparison operator.
     * @param x CSMXP_V3 object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const CSMXP_V3& x) const;

    /*!
     * @brief Comparison operator.
     * @param x CSMXP_V3 object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const CSMXP_V3& x) const;

    /*!
     * @brief This function sets a value in member SRC
     * @param _SRC New value for member SRC
     */
    eProsima_user_DllExport void SRC(
            uint32_t _SRC);

    /*!
     * @brief This function returns the value of member SRC
     * @return Value of member SRC
     */
    eProsima_user_DllExport uint32_t SRC() const;

    /*!
     * @brief This function returns a reference to member SRC
     * @return Reference to member SRC
     */
    eProsima_user_DllExport uint32_t& SRC();

    /*!
     * @brief This function sets a value in member DST
     * @param _DST New value for member DST
     */
    eProsima_user_DllExport void DST(
            uint32_t _DST);

    /*!
     * @brief This function returns the value of member DST
     * @return Value of member DST
     */
    eProsima_user_DllExport uint32_t DST() const;

    /*!
     * @brief This function returns a reference to member DST
     * @return Reference to member DST
     */
    eProsima_user_DllExport uint32_t& DST();

    /*!
     * @brief This function copies the value in member MSG
     * @param _MSG New value to be copied in member MSG
     */
    eProsima_user_DllExport void MSG(
            const std::vector<uint8_t>& _MSG);

    /*!
     * @brief This function moves the value in member MSG
     * @param _MSG New value to be moved in member MSG
     */
    eProsima_user_DllExport void MSG(
            std::vector<uint8_t>&& _MSG);

    /*!
     * @brief This function returns a constant reference to member MSG
     * @return Constant reference to member MSG
     */
    eProsima_user_DllExport const std::vector<uint8_t>& MSG() const;

    /*!
     * @brief This function returns a reference to member MSG
     * @return Reference to member MSG
     */
    eProsima_user_DllExport std::vector<uint8_t>& MSG();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const CSMXP_V3& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    uint32_t m_SRC;
    uint32_t m_DST;
    std::vector<uint8_t> m_MSG;
};

#endif // _FAST_DDS_GENERATED_CSMXP_V3_H_