// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CSMXP_V3.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "CSMXP_V3.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

CSMXP_V3::CSMXP_V3()
{
    // m_SRC com.eprosima.idl.parser.typecode.PrimitiveTypeCode@dc24521
    m_SRC = 0;
    // m_DST com.eprosima.idl.parser.typecode.PrimitiveTypeCode@10bdf5e5
    m_DST = 0;
    // m_MSG com.eprosima.idl.parser.typecode.SequenceTypeCode@6e1ec318


}

CSMXP_V3::~CSMXP_V3()
{



}

CSMXP_V3::CSMXP_V3(
        const CSMXP_V3& x)
{
    m_SRC = x.m_SRC;
    m_DST = x.m_DST;
    m_MSG = x.m_MSG;
}

CSMXP_V3::CSMXP_V3(
        CSMXP_V3&& x)
{
    m_SRC = x.m_SRC;
    m_DST = x.m_DST;
    m_MSG = std::move(x.m_MSG);
}

CSMXP_V3& CSMXP_V3::operator =(
        const CSMXP_V3& x)
{

    m_SRC = x.m_SRC;
    m_DST = x.m_DST;
    m_MSG = x.m_MSG;

    return *this;
}

CSMXP_V3& CSMXP_V3::operator =(
        CSMXP_V3&& x)
{

    m_SRC = x.m_SRC;
    m_DST = x.m_DST;
    m_MSG = std::move(x.m_MSG);

    return *this;
}

bool CSMXP_V3::operator ==(
        const CSMXP_V3& x) const
{

    return (m_SRC == x.m_SRC && m_DST == x.m_DST && m_MSG == x.m_MSG);
}

bool CSMXP_V3::operator !=(
        const CSMXP_V3& x) const
{
    return !(*this == x);
}

size_t CSMXP_V3::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (1450 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);




    return current_alignment - initial_alignment;
}

size_t CSMXP_V3::getCdrSerializedSize(
        const CSMXP_V3& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.MSG().size() > 0)
    {
        current_alignment += (data.MSG().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void CSMXP_V3::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_SRC;
    scdr << m_DST;
    scdr << m_MSG;

}

void CSMXP_V3::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_SRC;
    dcdr >> m_DST;
    dcdr >> m_MSG;
}

/*!
 * @brief This function sets a value in member SRC
 * @param _SRC New value for member SRC
 */
void CSMXP_V3::SRC(
        uint32_t _SRC)
{
    m_SRC = _SRC;
}

/*!
 * @brief This function returns the value of member SRC
 * @return Value of member SRC
 */
uint32_t CSMXP_V3::SRC() const
{
    return m_SRC;
}

/*!
 * @brief This function returns a reference to member SRC
 * @return Reference to member SRC
 */
uint32_t& CSMXP_V3::SRC()
{
    return m_SRC;
}

/*!
 * @brief This function sets a value in member DST
 * @param _DST New value for member DST
 */
void CSMXP_V3::DST(
        uint32_t _DST)
{
    m_DST = _DST;
}

/*!
 * @brief This function returns the value of member DST
 * @return Value of member DST
 */
uint32_t CSMXP_V3::DST() const
{
    return m_DST;
}

/*!
 * @brief This function returns a reference to member DST
 * @return Reference to member DST
 */
uint32_t& CSMXP_V3::DST()
{
    return m_DST;
}

/*!
 * @brief This function copies the value in member MSG
 * @param _MSG New value to be copied in member MSG
 */
void CSMXP_V3::MSG(
        const std::vector<uint8_t>& _MSG)
{
    m_MSG = _MSG;
}

/*!
 * @brief This function moves the value in member MSG
 * @param _MSG New value to be moved in member MSG
 */
void CSMXP_V3::MSG(
        std::vector<uint8_t>&& _MSG)
{
    m_MSG = std::move(_MSG);
}

/*!
 * @brief This function returns a constant reference to member MSG
 * @return Constant reference to member MSG
 */
const std::vector<uint8_t>& CSMXP_V3::MSG() const
{
    return m_MSG;
}

/*!
 * @brief This function returns a reference to member MSG
 * @return Reference to member MSG
 */
std::vector<uint8_t>& CSMXP_V3::MSG()
{
    return m_MSG;
}

size_t CSMXP_V3::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;






    return current_align;
}

bool CSMXP_V3::isKeyDefined()
{
    return false;
}

void CSMXP_V3::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
       
}
