// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CSMXP_V3Subscriber.h
 * This header file contains the declaration of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#ifndef FASTDDS_GENERATED_CSMXP_V3_SUBSCRIBER_H_
#define FASTDDS_GENERATED_CSMXP_V3_SUBSCRIBER_H_

#include <fastdds/dds/domain/DomainParticipant.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/DataReaderListener.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include <fastdds/dds/topic/TypeSupport.hpp>
#include <string>
#include <vector>

class CSMXP_V3Subscriber
{
public:
    CSMXP_V3Subscriber();
    virtual ~CSMXP_V3Subscriber();

    // Initialize DDS subscriber
    bool init(int domainId, std::string topicName, std::string multicastIp, int port, int bDebug = false);

    // Clean up resources
    void uninit();

    // Run subscriber (blocking wait)
    void run();

    // Stop running
    void stop();

    // Callback function type definition for data reception
    typedef void (DataReceiver)(const std::vector<uint8_t>& data, void* userObject);

    // Set data receiver callback function
    void setDataReceiverFunction(DataReceiver* recFun, void* userObject);

    // Get publisher count
    int getPublisherCount() const;

    // Check connection status
    bool isConnected() const;

private:
    eprosima::fastdds::dds::DomainParticipant* participant_;
    eprosima::fastdds::dds::Subscriber* subscriber_;
    eprosima::fastdds::dds::Topic* topic_;
    eprosima::fastdds::dds::DataReader* reader_;
    eprosima::fastdds::dds::TypeSupport type_;

    bool debugMode_;
    bool isRunning_;

    // Internal listener class
    class SubListener : public eprosima::fastdds::dds::DataReaderListener
    {
    public:
        // Callback for data reception
        DataReceiver* dataReceiverFun = nullptr;
        void* receiver = nullptr;
        bool debugMode = false;

        SubListener() = default;
        ~SubListener() override = default;

        // Data available callback
        void on_data_available(
                eprosima::fastdds::dds::DataReader* reader) override;

        // Subscription matched callback
        void on_subscription_matched(
                eprosima::fastdds::dds::DataReader* reader,
                const eprosima::fastdds::dds::SubscriptionMatchedStatus& info) override;

        // Get matched publisher count
        int getMatchedCount() const { return matched; }

        // Get received sample count
        uint32_t getSampleCount() const { return samples; }

    private:
        int matched = 0;
        uint32_t samples = 0;
    }
    listener_;
};

#endif // FASTDDS_GENERATED_CSMXP_V3_SUBSCRIBER_H_







