// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CSMXP_V3Subscriber.cpp
 * This file contains the implementation of the subscriber functions.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/subscriber/DataReader.hpp>
#include <fastdds/dds/subscriber/SampleInfo.hpp>
#include <fastdds/dds/subscriber/Subscriber.hpp>
#include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
#include<fastdds/rtps/transport/UDPv4TransportDescriptor.h>
#include<fastdds/rtps/transport/shared_mem/SharedMemTransportDescriptor.h>

#include "CSMXP_V3Subscriber.h"
#include "CSMXP_V3PubSubTypes.h"

#include <iostream>
#include <fstream>
#include <sstream>
using namespace eprosima::fastdds::dds;

CSMXP_V3Subscriber::CSMXP_V3Subscriber()
    : participant_(nullptr)
    , subscriber_(nullptr)
    , topic_(nullptr)
    , reader_(nullptr)
    , type_(new CSMXP_V3PubSubType())
{
}

CSMXP_V3Subscriber::~CSMXP_V3Subscriber()
{
    uninit();
}

void CSMXP_V3Subscriber::uninit()
{
    if (reader_ != nullptr)
    {
        subscriber_->delete_datareader(reader_);
        reader_ = nullptr;
    }
    
    if (subscriber_ != nullptr)
    {
        participant_->delete_subscriber(subscriber_);
        subscriber_ = nullptr;
    }

    if (topic_ != nullptr)
    {
        participant_->delete_topic(topic_);
        topic_ = nullptr;
    }

    if (participant_ != nullptr)
    {
        DomainParticipantFactory::get_instance()->delete_participant(participant_);
        participant_ = nullptr;
    }
    
}

bool CSMXP_V3Subscriber::init(int id, std::string topic, std::string multicastIp, int port, int bDebug)
{
    
    //CREATE THE PARTICIPANT
    DomainParticipantQos pqos;
    pqos.name("Participant_sub");
    //Qos策略配置
    // Create a descriptor for the new transport.
    auto udp_transport = std::make_shared<eprosima::fastdds::rtps::UDPv4TransportDescriptor>();
    // 设置网络传输数据包的最大大小，例如 65536 字节
    udp_transport->maxMessageSize = 65536; // 设置最大消息大小
    udp_transport->sendBufferSize= 524288; // 设置发送缓冲区大小
    udp_transport->receiveBufferSize = 2097152; // 设置接收缓冲区大小  
    udp_transport->non_blocking_send = true;  //非阻塞发送(异步发送数据)
    udp_transport->TTL = 5;
    // 创建共享内存传输描述符
    auto shmem_transport = std::make_shared<eprosima::fastdds::rtps::SharedMemTransportDescriptor>();
    // 设置共享内存传输的最大消息大小
    shmem_transport->segment_size(2 * 9216); // 设置共享内存段的大小，通常需要比最大消息大小大
    shmem_transport->maxMessageSize = 9216; // 设置最大消息大小
    // 设置最大初始peer范围（可选）
    shmem_transport->maxInitialPeersRange = 50;
    //std::ifstream file("DEFAULT_QOS_PROFILES.xml");
    //if(!file.good()) {
    //    std::cerr << "XML文件不存在或无法访问!" << std::endl;
    //}
    //else
    //{
    //    // 打印文件内容
    //    std::stringstream buffer;
    //    buffer << file.rdbuf();
    //    std::cout << "XML文件内容:\n" << buffer.str() << std::endl;
    //}

    //if (ReturnCode_t::RETCODE_OK == DomainParticipantFactory::get_instance()->load_XML_profiles_file("DEFAULT_QOS_PROFILES.xml"))
    //{
    //    std::cout << "配置文件加载成功" << std::endl;
    //}
    //else
    //{
    //    std::cout << "配置文件加载失败" << std::endl;
    //}
    
    //pqos.transport().use_builtin_transports = false; // 禁用内置传输 会造成程序退出(禁用)
    pqos.transport().send_socket_buffer_size = 524288;  // sending buffer size
    pqos.transport().listen_socket_buffer_size = 2097152;  // receiving buffer size
   
    //非调试模式下指定组播地址
    if (!bDebug)
    {
        // 创建Locator_t对象来设置组播地址
        eprosima::fastrtps::rtps::Locator_t multicast_locator;
        multicast_locator.kind = LOCATOR_KIND_UDPv4;
        // 设置组播地址为224.100.200.101 和端口 0
        eprosima::fastrtps::rtps::IPLocator::setIPv4(multicast_locator, multicastIp);
        multicast_locator.port = port;  //端口要和发布端保持一致，否则不能被发现
        // 将组播Locator添加到参与者QoS的metatrafficMulticastLocatorList
        pqos.wire_protocol().builtin.metatrafficMulticastLocatorList.push_back(multicast_locator);
    }
   
    //以上配置Qos结束 end
    //创建
    participant_ = DomainParticipantFactory::get_instance()->create_participant(id, pqos);
    if (participant_ == nullptr)
    {
        return false;
    }

    //REGISTER THE TYPE
    type_.register_type(participant_);

    //CREATE THE SUBSCRIBER
    subscriber_ = participant_->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr);
    if (subscriber_ == nullptr)
    {
        return false;
    }

    //CREATE THE TOPIC
    std::cout << "订阅主题:" << topic << std::endl;
    topic_ = participant_->create_topic(topic,type_.get_type_name(),TOPIC_QOS_DEFAULT);

    if (topic_ == nullptr)
    {
        return false;
    }

    //CREATE THE READER
    DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
    //rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
    rqos.reliability().kind = BEST_EFFORT_RELIABILITY_QOS;
    rqos.reliable_reader_qos().times.heartbeatResponseDelay = Duration_t(0, 0); // 设置心跳响应延迟为0
    reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
    if (reader_ == nullptr)
    {
        return false;
    }

    return true;
}

void CSMXP_V3Subscriber::SubListener::on_subscription_matched(
        DataReader*,
        const SubscriptionMatchedStatus& info)
{
    if (info.current_count_change == 1)
    {
        matched = info.total_count;
        std::cout << "Subscriber matched." << std::endl;
    }
    else if (info.current_count_change == -1)
    {
        matched = info.total_count;
        std::cout << "Subscriber unmatched." << std::endl;
    }
    else
    {
        std::cout << info.current_count_change
                  << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
    }
}

void CSMXP_V3Subscriber::SubListener::on_data_available(DataReader* reader)
{
    // Take data
    CSMXP_V3 st;
    SampleInfo info;
    if (reader->take_next_sample(&st, &info) == ReturnCode_t::RETCODE_OK)
    {
        if (info.valid_data)
        {
            // Print your structure data here.
            ++samples;
            std::cout << "Sample received, count=" << samples << std::endl;
            //std::cout << "接受报文:" <<st.message()<< std::endl;
            // 数据发送
            int dataLen = st.MSG().size();
            std::vector<uint8_t> msg = st.MSG();
            if (st.MSG().size() > 0 && dataLen < 65535 &&dataReceiverFun != nullptr)
            {
                char* res = new char[dataLen];
               
                // vector<uint8_t> 转换到 char *
                uint8_t* tmp = st.MSG().data();
                memcpy(res, tmp, dataLen);
                for (int i = 0; i < dataLen; i++)
                {
                    char tempStr = res[i];
                    //std::cout << res[i] <<std::endl;
                }
                // 回调调用
                (*dataReceiverFun)(res, dataLen, receiver);
                
            }
            
        }
    }
}

void CSMXP_V3Subscriber::run()
{
    std::cout << "Waiting for Data, press Enter to stop the DataReader. " << std::endl;
    std::cin.ignore();
    std::cout << "Shutting down the Subscriber." << std::endl;
}
void CSMXP_V3Subscriber::setDataReceiverFunction(DataReceiver* recFun, void* rec)
{
    listener_.dataReceiverFun = recFun;
    listener_.receiver = rec;
}